### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by georgiewellock** [arc-lessons/funcs-classes-python#1]
Typo in dictionaries notebook. 
"Questions
     What is a dictioanry?"

**Comment by georgiewellock** [comment]
Typos in github-testing-ci

- Branching - Information - 'behaviours'
- Remotes - Authentication - 'password'
- Pull requests - What is a pull request - 'providers' and 'successes'
- Testing - Key points - 'unwritten' and 'because'

**Comment by james-grant1** [comment]
Typo dictionary typo fixed, second issue if for github... repo, raising there.
